allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: true
allowedCapabilities:
- IPC_LOCK
allowedFlexVolumes: []
apiVersion: v1
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
groups:
- system:authenticated
- system:serviceaccounts:es-kafka
kind: SecurityContextConstraints
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowHostDirVolumePlugin":false,"allowHostIPC":false,"allowHostNetwork":false,"allowHostPID":false,"allowHostPorts":false,"allowPrivilegedContainer":true,"allowedCapabilities":["FOWNER","CHOWN","SETGID","DACOVERRIDE","SETFCAP","SYS_MODULE","SYS_RESOURCE"],"allowedFlexVolumes":[],"apiVersion":"v1","defaultAddCapabilities":[],"fsGroup":{"ranges":[{"max":1000,"min":1000}],"type":"MustRunAs"},"groups":["system:authenticated","system:serviceaccounts:es-kafka"],"kind":"SecurityContextConstraints","metadata":{"annotations":{"kubernetes.io/description":"privileged allows access to all privileged and host features and the ability to run as any user, any group, any fsGroup, and with any SELinux context.  WARNING: this is the most relaxed SCC and should be used only for cluster administration. Grant with caution."},"creationTimestamp":null,"name":"es-privileged","namespace":""},"priority":11,"readOnlyRootFilesystem":false,"requiredDropCapabilities":[],"runAsUser":{"type":"MustRunAs","uid":1000},"seLinuxContext":{"type":"RunAsAny"},"seccompProfiles":["*"],"supplementalGroups":{"ranges":[{"max":1000,"min":1000}],"type":"MustRunAs"},"users":["system:serviceaccount:es-kafka:es-sa"],"volumes":["configMap","downwardAPI","emptyDir","persistentVolumeClaim","projected","secret"]}
    kubernetes.io/description: 'privileged allows access to all privileged and host
      features and the ability to run as any user, any group, any fsGroup, and with
      any SELinux context.  WARNING: this is the most relaxed SCC and should be used
      only for cluster administration. Grant with caution.'
  creationTimestamp: null
  name: es-privileged
priority: 11
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  ranges:
  - max: 1000
    min: 1000
  type: MustRunAs
users:
- system:serviceaccount:es-kafka:es-sa
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- persistentVolumeClaim
- projected
- secret
